---
abstract: 'a great new dist'
author:
  - 'LOCAL <LOCAL@cpan.local>'
build_requires: {}
dynamic_config: 0
generated_by: 'CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: P
provides:
  P:
    file: lib/P.pm
    version: v1.0.20
version: v1.0.20
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
