---
abstract: 'Include a __DATA__ token inside a pod block'
author:
  - 'BORISNAT <BORISNAT@cpan.local>'
build_requires: {}
dynamic_config: 0
generated_by: 'CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pod-With-Data-Token
provides:
  Pod::With::Data::Token:
    file: lib/Pod/With/Data/Token.pm
    version: '0.01'
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
