---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: 'weekly'
    groups:
      major-updates:
        patterns:
          - '*'
        update-types:
          - 'major'
      minor-and-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    cooldown:
      default-days: 7
  - package-ecosystem: 'docker-compose'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'elasticsearch'
        update-types: 'version-update:semver-major'
    groups:
      minor-and-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    cooldown:
      default-days: 7
