#!/usr/bin/env perl

use strict;
use warnings;
use Config;
# Hack to use carton's local::lib.
use lib 'local/lib/perl5';
$ENV{PATH} .= $Config{path_sep}.'local/bin';
$ENV{PERL5LIB} = join $Config{path_sep},
  grep defined, $ENV{PERL5LIB}, 'local/lib/perl5';

use Code::TidyAll::Git::Precommit;
Code::TidyAll::Git::Precommit->check( no_stash => 1 );
