---
abstract: 'A dist with a single license'
author:
  - 'RWSTAUNER <RWSTAUNER@cpan.local>'
build_requires: {}
dynamic_config: 0
generated_by: 'CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Meta-License-Single
provides:
  Meta::License::Single:
    file: lib/Meta/License/Single.pm
    version: '1.0'
version: '1.0'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
