---
abstract: 'A dist with a Changes file in ISO 8859-1'
author:
  - 'RWSTAUNER <RWSTAUNER@cpan.local>'
build_requires: {}
dynamic_config: 0
generated_by: 'CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Changes-Latin1
provides:
  File::Changes::Latin1:
    file: lib/File/Changes/Latin1.pm
    version: '1.0'
version: '1.0'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
