---
abstract: 'contains various scripts that should be declared as such'
author:
  - 'MO <MO@cpan.local>'
build_requires: {}
dynamic_config: 0
generated_by: 'CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Scripts
provides:
  Scripts:
    file: lib/Scripts.pm
    version: '0.01'
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
