---
abstract: 'A dist that depends on Multiple::Modules::A'
author:
  - 'LOCAL <LOCAL@cpan.local>'
build_requires: {}
dynamic_config: 0
generated_by: 'CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Multiple-Modules-RDeps-A
provides:
  Multiple::Modules::RDeps::A:
    file: lib/Multiple/Modules/RDeps/A.pm
    version: '2.03'
requires:
  Multiple::Modules::A: '0'
version: 2.03
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
