---
abstract: 'A dist that Multiple::Modules::* can use for testing'
author:
  - 'LOCAL <LOCAL@cpan.local>'
build_requires: {}
dynamic_config: 0
generated_by: 'CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Multiple-Modules-Tester
provides:
  Multiple::Modules::Tester:
    file: lib/Multiple/Modules/Tester.pm
    version: '0.96'
version: 0.96
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
