---
abstract: 'a great new dist'
author:
  - 'LOCAL <LOCAL@cpan.local>'
build_requires: {}
dynamic_config: 0
generated_by: 'CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Tabs+Wrap
provides: {}
version: '2013.0523'
x_serialization_backend: 'CPAN::Meta::YAML version 0.020'
